defaults: &defaults
    adapter: sqlite3
    encoding: unicode

development:
    <<: *defaults
    database: db/development.sqlite

test:
    <<: *defaults
    database: db/test.sqlite

production:
    <<: *defaults
    database: db/wheel.sqlite
